app:
  # A helpful name for identifying multiple runs from this config
  name: insert traces 2 GiB/s
  log_level: debug
  log_to_console: true
  log_to_file: false
  # Determines the data type being read/inserted for the test. One of: logs, traces
  data_type: traces
  # A seed for the test. Will be used with random number generation for reproducible tests.
  seed: some string

disk:
  enabled: true
  threads: 4
  # Path to logs/traces directories. Files must be named .native or .native.zst
  logs_path: log_data
  traces_path: trace_data
  # Blocks can be reused to reduce garbage in the program and improve throughput stability, but
  # ch-go has a bug where some columns aren't properly reset. I've hacked around this for now and so
  # you shouldn't notice it, but maybe I missed a detail when querying the data back.
  # Set this to false if you notice the inserted data has maps that have mismatched key/value pairs, or empty columns.
  reuse_blocks: true
  # Should the file queue be looped? (Consider the shift_timestamp setting. May cause uneven distribution of data.)
  # Also consider the thread count.
  # If there are more threads than files, the looped files will immediately go in the queue.
  loop: false
  # The speed limit for uncompressed data across all threads, in MiB
  mb_per_second_limit: 2048
  # Shifts the timestamp of the data when reading from disk.
  # Options: <empty>, none, date, all, now.
  # Empty/"none" will do nothing and replay the data as it is written on disk. Event times will be unchanged.
  # "date" will replace only the date component with the current date.
  #        The event timestamp will keep its time component, but with the current date.
  #        This may cause issues if your data set goes across multiple days.
  # "all" will replay the data with its original timings by measuring the difference between the
  #       event time and the first timestamp in the first file loaded. This difference is then added to the
  #       program start time.
  #       It's replaying the original data but with the first event time being the program start time.
  #       If looping is enabled, the program will track the range of time that the dataset covers and account
  #       for its duration between loops.
  #       There may be some overlap where the first files end and the looped file queue starts.
  # "now" will simply set the event time to the current timestamp at the time the row is processed.
  #       This may lead to unrealistic time distributions where an entire block of rows share the same timestamp.
  shift_timestamp: all

insert:
  enabled: false
  threads: 4
  # How many rows per INSERT command. Blocks will be streamed until this limit, then a new INSERT will start.
  # After this limit is reached, the current block will finish sending and then end the INSERT, therefore it's not
  # an exact limit.
  batch_size: 100000
  balance_nodes: false
  clickhouse:
    address: localhost:9000
    secure: false
    user: default
    password:
    # One of: none, lz4, zstd, lz4hc
    # This will affect Insert Bytes metric
    compression:
    # Database and tables to insert into
    database: otel
    logs_table: otel_logs
    traces_table: otel_traces


# Settings related to the program's read/insert metrics
metrics:
  enabled: true
  # ClickHouse DSN URL, same as OTel exporter. Optional, if empty then metrics won't be stored.
  clickhouse_dsn: tcp://localhost:9000
  # Database and tables for capturing performance metrics, these are created automatically.
  database: otelspam
  run_table: runs
  metrics_table: perf

user:
  enabled: true
  threads: 10
  connections_per_user: 2
  # ClickHouse DSN URL, same as OTel exporter.
  clickhouse_dsn: tcp://localhost:9000
  # The database to query from
  database: otelspam
  logs_table: otel_logs
  traces_table: otel_traces
  min_query_wait: 1s
  max_query_wait: 10s
  # Queries is an array of queries that will be chosen by the user worker
  queries:
    # This SQL is a Go templated string and has some variables available.
    # "FORMAT Null" is automatically appended to the end so that no query data is returned to the client.
    # These variables are already SQL compatible and do not need quotes or escaping. See examples.
    # Available values:
    #  Table: the fully qualified database and table name: "example"."database"
    #  TimeRangeStart: the start of the time range (current time minus the configured time_range): fromUnixTimestamp64Milli(...)
    #  TimeRangeEnd: the end of the time range (the current time of the query being executed): fromUnixTimestamp64Milli(...)
    #
    # To use, use Go template syntax: {{.VariableName}}
    #
    - name: test
      sql: "SELECT * FROM {{.Table}} WHERE timestamp >= {{.TimeRangeStart}} AND timestamp <= {{.TimeRangeEnd}}"
      # Time range is optional, but can be used to populate the time range variables in the above SQL.
      # The end time will be equal to the current time when the query is executed.
      # The start time will be the current time minus the time_range duration below.
      # You should have read.time_shift set to "all" for this to work as expected.
      time_range: 15m
    - sql: "SELECT 2"
    - sql: "SELECT 3"

