app:
  log_level: debug
  log_to_console: true
  log_to_file: true
  # Determines the data type being read/inserted for the test. One of: logs, traces
  data_type: traces
  # A seed for the test. Will be used with random number generation for reproducible tests.
  seed: some string

disk:
  enabled: true
  threads: 2
  # Path to logs/traces directories. Files must be named .native or .native.zst
  logs_path: log_data
  traces_path: trace_data
  # The speed limit for uncompressed data across all threads, in MiB
  mb_per_second_limit: 2048
  # Shifts the timestamp of the data when reading from disk.
  # Options: <empty>, none, date, all, now.
  # Empty/"none" will do nothing and replay the data as it is written on disk. Event times will be unchanged.
  # "date" will replace only the date component with the current date. The event timestamp will keep its time component, but with the current date.
  # "all" will replay the data with its original timings by measuring the difference between the event time and the first timestamp in the first file loaded.
  # "now" will simply set the event time to the current timestamp.
  shift_timestamp: all

insert:
  enabled: true
  threads: 4
  # How many rows per INSERT command. Blocks will be streamed until this limit, then a new INSERT will start.
  # After this limit is reached, the current block will finish sending and then end the INSERT, therefore it's not
  # an exact limit.
  batch_size: 100000
  balance_nodes: false
  clickhouse:
    address: localhost:9000
    secure: false
    user: default
    password:
    # One of: none, lz4, zstd, lz4hc
    # This will affect Insert Bytes metric
    compression:
    # Database and tables to insert into
    database: otel
    logs_table: otel_logs
    traces_table: otel_traces


# Settings related to the program's read/insert metrics
metrics:
  enabled: true
  # ClickHouse DSN URL, same as OTel exporter. Optional, if empty then metrics won't be stored.
  clickhouse_dsn: tcp://localhost:9000
  # Database and tables for capturing performance metrics, these are created automatically.
  database: otelspam
  run_table: runs
  metrics_table: perf

user:
  enabled: true
  threads: 10
  connections_per_user: 2
  # ClickHouse DSN URL, same as OTel exporter.
  clickhouse_dsn: tcp://localhost:9000
  # The database to query from
  database: otelspam
  logs_table: otel_logs
  traces_table: otel_traces
  min_query_wait: 1s
  max_query_wait: 10s

